"""
kms_service.py – AWS KMS envelope encryption for all PII data.

Architecture:
  • A Data Encryption Key (DEK) is generated by KMS (GenerateDataKey).
  • The plaintext DEK encrypts the field value using AES-256-GCM locally.
  • We store: base64( encrypted_DEK || iv || tag || ciphertext ).
  • On decrypt: KMS decrypts the DEK, then AES-GCM decrypts the payload.

This means only 1 KMS API call per encrypt/decrypt (envelope pattern),
keeping latency low and costs minimal.
"""
import base64
import json
import os
import boto3
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from config import get_settings

settings = get_settings()


def _kms_client():
    return boto3.client(
        "kms",
        region_name=settings.aws_region,
        aws_access_key_id=settings.aws_access_key_id or None,
        aws_secret_access_key=settings.aws_secret_access_key or None,
    )


# ─── Encrypt ─────────────────────────────────────────────────────────────────

def kms_encrypt(plaintext: str) -> str:
    """
    Encrypt *plaintext* using AWS KMS envelope encryption.
    Returns a base64url-encoded JSON blob containing:
      encrypted_dek, iv, tag, ciphertext  (all base64).
    """
    if not plaintext:
        return plaintext

    # 1. Ask KMS for a fresh DEK
    kms = _kms_client()
    response = kms.generate_data_key(
        KeyId=settings.kms_key_id,
        KeySpec="AES_256",
    )
    plaintext_dek: bytes = response["Plaintext"]        # 32 bytes – use in memory only
    encrypted_dek: bytes = response["CiphertextBlob"]   # store alongside data

    # 2. Encrypt the value locally with AES-256-GCM
    iv = os.urandom(12)                                 # 96-bit nonce
    aesgcm = AESGCM(plaintext_dek)
    ciphertext_with_tag = aesgcm.encrypt(iv, plaintext.encode("utf-8"), None)
    # AESGCM appends the 16-byte auth tag to the ciphertext
    ciphertext = ciphertext_with_tag[:-16]
    tag        = ciphertext_with_tag[-16:]

    # 3. Serialise into a single storable blob
    envelope = {
        "v": 1,
        "dek": base64.b64encode(encrypted_dek).decode(),
        "iv":  base64.b64encode(iv).decode(),
        "tag": base64.b64encode(tag).decode(),
        "ct":  base64.b64encode(ciphertext).decode(),
    }
    return base64.b64encode(json.dumps(envelope).encode()).decode()


# ─── Decrypt ─────────────────────────────────────────────────────────────────

def kms_decrypt(cipherblob: str) -> str:
    """
    Decrypt a cipherblob produced by kms_encrypt().
    Returns the original plaintext string.
    """
    if not cipherblob:
        return cipherblob

    # 1. Unpack the envelope
    envelope = json.loads(base64.b64decode(cipherblob))
    encrypted_dek = base64.b64decode(envelope["dek"])
    iv            = base64.b64decode(envelope["iv"])
    tag           = base64.b64decode(envelope["tag"])
    ciphertext    = base64.b64decode(envelope["ct"])

    # 2. Ask KMS to decrypt the DEK
    kms = _kms_client()
    response = kms.decrypt(
        KeyId=settings.kms_key_id,
        CiphertextBlob=encrypted_dek,
    )
    plaintext_dek: bytes = response["Plaintext"]

    # 3. Decrypt the payload
    aesgcm = AESGCM(plaintext_dek)
    plaintext_bytes = aesgcm.decrypt(iv, ciphertext + tag, None)
    return plaintext_bytes.decode("utf-8")


# ─── Batch helpers ────────────────────────────────────────────────────────────

def encrypt_pii_fields(data: dict, fields: list[str]) -> dict:
    """Encrypt specified fields in *data* in-place. Returns modified dict."""
    for field in fields:
        if data.get(field) is not None:
            data[field] = kms_encrypt(str(data[field]))
    return data


def decrypt_pii_fields(data: dict, fields: list[str]) -> dict:
    """Decrypt specified fields in *data* in-place. Returns modified dict."""
    for field in fields:
        if data.get(field) is not None:
            try:
                data[field] = kms_decrypt(data[field])
            except Exception:
                data[field] = "[DECRYPTION ERROR]"
    return data
